### ISSUE TITLE
Windows系统全局http代理似乎有断流现象

### ISSUE THREAD

**Issue by lqdflying** [sipt/shuttle#10]
系统环境：Win10专业版 1803 shuttle最新release版
疑似问题描述：Windows系统全局http代理似乎有断流现象
疑似问题发现过程：Windows系统全局代理的情况下，telegram的UI左下角经常转圈[转圈一般是代表tg在重新建立连接]，发生频率大约10分钟一次，恢复时间3-5秒。
尝试解决过程：tg软件直接配置socks5代理后就没有断流。
其他系统代理模式下的软件表现：sstap，ssr，SSD均在系统代理的模式下未发现断流

**Comment by sipt** [comment]
这个应该是因为在HTTP/HTTPS代理的情况下，比如Chrome会复用连接，并不主动关闭连接，导致连接数过多，所以加入了10s超时，10s内没有数据传输就会关闭连接，下次需要重新建立。而rtt评估是10min一次，赶上服务器切换，所以就可能出现上述情况。而在socks通信中并没有加入相关的超时机制，只有客户端/服务器端主动关闭。所以现在的建议就是给telegram单独配置socks。后期我考虑如何优化。

**Comment by lqdflying** [comment]
感谢大佬，了解了
