### ISSUE TITLE
希望增加 GCM 相关加密算法支持

### ISSUE THREAD

**Issue by tingxueren** [sipt/shuttle#14]
如题，aes-256-gcm 等加密算法并不支持，导致无法使用，辛苦支持。

**Comment by sipt** [comment]
@tingxueren
chacha20-ietf-poly1305
aes-256-gcm
aes-192-gcm
aes-128-gcm
beta-v0.3.2中已经支持， #22

**Comment by tingxueren** [comment]
十分感谢，明天我试试
