### ISSUE TITLE
疑似BUG提交，HTTP系统代理的情况下，同一个域名内部做了二次跳转的话，shuttle似乎会提示“意外终止连接”

### ISSUE THREAD

**Issue by lqdflying** [sipt/shuttle#26]
系统：win10专业版最新版
配置：2组rtt节点，每组约10个。、
BUG疑似：HTTP系统代理的情况下，同一个域名内部做了二次跳转的话，shuttle似乎会提示“意外终止连接”
测试使用情景：打开https://my.90vm.com/clientarea.php?action=services正常，打开https://my.90vm.com/clientarea.php?action=productdetails&id=65失败。
目前测试的过程：
咨询厂商，似乎他们https://my.90vm.com/clientarea.php?action=services是在国内，https://my.90vm.com/clientarea.php?action=productdetails&id=65会内部跳转到美国的服务器。
**相同的规则，手机+surge可以正常打开。PC+http系统代理无法打开。**
我有90vm的VPS，作者如果想测试这个问题，可以提供我邮箱地址，我把我在90VM的账号密码贡献出来

**Comment by sipt** [comment]
排查下来，是因为此链接返回值太慢延迟太长，触发超时异常而中断连接。会考虑去掉超时机制

**Comment by lqdflying** [comment]
感谢大佬排查
