### ISSUE TITLE
一个奇怪的会串网站的问题？

### ISSUE THREAD

**Issue by doio** [sipt/shuttle#34]
不知道应该如何描述这个问题，
大概就是设置好以后，打开 https://www.google.com
然后在相同地址栏打开一个 HTTP 链接，如 http://example.com
然后就立刻显示网页 404 不存在，以为 https://www.google.com 上面没有相关的资源

打开其他 HTTPS 网站以后再在地址栏打开 HTTP 网站也会出现类似问题

好像 HTTP 网站都会出现问题，例如打开 http://httpd.apache.org/ 直接显示 Cloudflare 的 403 Error

打开 mail.qq.com 的时候会跳转到 https，然后过一会就跳转到 http，结果也显示 The requested URL '/cgi-bin/frame_html' was not found on this server. 

另外有时候 shuttle 会卡住一会，打不开网页。

**Comment by sipt** [comment]
排查是Firefox浏览器连接复重导致，后期修复。建议先使用Chrome

**Comment by sipt** [comment]
#46 修复单连接复用问题
