### ISSUE TITLE
恭喜新版发布了, 找个地方显示版本号吧

### ISSUE THREAD

**Issue by vmvz** [sipt/shuttle#47]
例如
![image](https://user-images.githubusercontent.com/1652700/46659864-5a249c00-cbe8-11e8-8422-d81bc8334ebf.png)

**Comment by sipt** [comment]
Alpha_v0.5.0(测试中): 支持版本检查和一键更新。
![image](https://user-images.githubusercontent.com/10202695/46662532-467c3400-cbee-11e8-97b2-2a7a07037ae8.png)
可以加入 Telegram 下载体验。
