### ISSUE TITLE
windows10 v0.5.1 尝试修改dns server，不起作用。默认还是从114.114.114.114和223.5.5.5开始解析的

### ISSUE THREAD

**Issue by showchi** [sipt/shuttle#50]
windows10 v0.5.1 尝试修改dns server，不起作用。默认还是从114.114.114.114和223.5.5.5开始解析的

**Comment by sipt** [comment]
DNS解析机制是：同时请求dns-server 下配置的所有DNS服务器地址，哪个先返回先用哪个。目的加快DNS解析

**Comment by showchi** [comment]
但是我注销掉114和223的dns，仅保留8.8.8.8，重新载入配置，查看cache中的数据还是显示114或者223解析的

**Comment by sipt** [comment]
@showchi 
v0.5.1开始配置文件移置`~\Documents\shuttle\shuttle.yaml`
