### ISSUE TITLE
shuttle出现闪退

### ISSUE THREAD

**Issue by lqdflying** [sipt/shuttle#6]
系统：win10专业版最新版
配置：2组rtt节点，每组约10个。
使用情景：系统代理情况下看Netflix时，出现闪退

**Comment by lqdflying** [comment]
请问需要开debug模式吗？我日志生成太大，就调整为了info模式？
如果需要开debug模式，我就重新打开，然后尝试复现问题

**Comment by sipt** [comment]
首先感谢你的使用和配合，基于你提供的log文件，目前还无法排查出闪退的原因，十分抱歉。现在还处于beta版本所以可能会存在一些Bug，后期我也会留意你描述的情况。但也希望在你有时间的情况下留意一下这个问题的复现，thanks!

**Comment by lqdflying** [comment]
2018-8-27 23:47:40再次闪退
日志如下：
https://transfer.sh/xB7X9/shuttle-quit-suddenly-2018-8-27-234646.log

**Comment by sipt** [comment]
目前无还未确定闪退原因，内测两周也未发现问题，如有复现再开启
Thanks!
