### ISSUE TITLE
rule规则更新提交

### ISSUE THREAD

**Issue by lqdflying** [sipt/shuttle#7]
大佬好。您git里自带的规则其实有一些疏漏，举例来说：
- ["DOMAIN-SUFFIX", "netflix.com", "nProxy", ""]
- ["DOMAIN-SUFFIX", "netflix.net", "nProxy", ""]
实际上应该是Proxy才对，因为大陆不能看NF，得代理才行。
我结合我目前使用的所有机场订阅的surge规则，制作了一版新的rule，完全匹配您的软件，并且规则最全面，亲测匹配99%的场景。
share给大佬。
https://transfer.sh/Fr8OP/shuttle.yaml

**Comment by sipt** [comment]
已添加， #22 
Thanks!
