### ISSUE TITLE
大佬还在维护这个项目吗

### ISSUE THREAD

**Issue by superqinwei** [sipt/shuttle#85]
大佬还在维护这个项目吗

**Comment by hexd2019** [comment]
不错的项目.可惜

**Comment by leyle** [comment]
有大佬接手继续维护吗？

**Comment by sipt** [comment]
前段时间尝试重构，但因为工作原因，还没完成（v2分支），年前应该可以肝出来

**Comment by superqinwei** [comment]
期待

> 前段时间尝试重构，但因为工作原因，还没完成（v2分支），年前应该可以肝出来

期待变成surge，哪怕付费。

**Comment by GreatFireWall** [comment]
> 期待
> 
> > 前段时间尝试重构，但因为工作原因，还没完成（v2分支），年前应该可以肝出来
> 
> 期待变成surge，哪怕付费。

付费有 Win2Socks, 可以考虑下.
