### ISSUE TITLE
ver0.6.0 使用中一些问题汇总

### ISSUE THREAD

**Issue by takenusername** [sipt/shuttle#86]
- **[BUG]** 程序重启会还原 Proxy Group 选择，比如 Proxy 组有 HKa、HKb，我选择了 HKb，按 Reload 后会还原为 HKa。
- **[BUG]** 程序有时会清除 yaml 配置文件里的注释（确定的是 WebUI 编辑规则应用后，其他情况排查不出了）。临时解决办法是用编辑器编辑，并用插件设置文件为只读属性。
- **[BUG]** webUI 里添加任一匹配时会点应用会 500 错误。
- **[BUG]** 使用中更换了节点再开网页会出现“连接已重置”现象，刷新一下才好。
- **[BUG]** 必须把所有节点添加到 Auto 组，才能显示所有节点的 ping 值。
- 已使用 Enable Loopback 解决。 ~~**[BUG]** 开启 shuttle ，windows 聚焦锁屏不更新壁纸，UWP 应用微软商店显示没有网络，UWP 的微信却可以联网。四个模式试过的情况下，确认规则没有涉及到 ### windows。~~ 
- **[Features request]** Records 页面请求条目倒序显示，且实时显示，不用滑到底查看最新条目。
- **[Features request]** Records 页面增加显示访问的网站 ip。
- **[Features request]** 加上 HOSTS 功能。软件会忽略本机 hosts 文件。
- **[Features request]** 支持 SSD 订阅。
- **[Features request]** 支持 v2ray。
- **[Features request]** 支持 xchacha20-ietf-poly1305 加密。
- **[Features request]** temp 文件夹可自定义路径。
- **[Features request]** 支持 URL-REGEX 匹配方式。
- **[Issues]** 关于 CSS。Proxy 页面 _div_ __ngcontent-c11_ 宽度固定 800px，对于宽屏浪费了很多横向空间，请设置为 min-width 或自动。
- 全局代理应该是无解了，如果能抓取网站 ip 并显示在 record 页面也是办法。  ~~**[Issues]** Chrome 有个扩展 [ipvfoo](https://github.com/pmarks-net/ipvfoo)，以前使用 SS 客户端都是用此扩展查看网站哪些资源被代理了。现在直连的网站都是到本地 127.0.0.1 ，除了一直盯着日志，有什么解决方案么？~~
例：B 站
第一张未开，第二张开 shuttle。
![B1](https://user-images.githubusercontent.com/7425161/72703110-b1f1d700-3b8f-11ea-81d1-7595c22f3018.jpg)
![B2](https://user-images.githubusercontent.com/7425161/72703133-c2a24d00-3b8f-11ea-936d-2dbcc0acbe00.jpg)

**Comment by sipt** [comment]
感谢反馈，shuttle 正在重构中，完成后将根据以上反馈问题进行校对，

**Comment by leyle** [comment]
期待大佬的作品。

**Comment by leyle** [comment]
@takenusername  这是完全放弃了吗，这么好的作品。
