### ISSUE TITLE
把 trojan 或 迷雾通作为 socks 上层代理使用时，出现如下错误 handShake failed: socks version not supported

### ISSUE THREAD

**Issue by leyle** [sipt/shuttle#87]
启动了 trojan 或者迷雾通，他们提供了 socks 打理，把 shuttle 里面的 socks 代理配置指向他们，
会出现 handShake failed: socks version not supported 错误。

**Comment by sipt** [comment]
目前shuttle只支持socks5，确认一下上层代理socks版本

**Comment by leyle** [comment]
> 目前shuttle只支持socks5，确认一下上层代理socks版本

找到原因了，上层代理死锁导致 goroutine 崩溃，所以 shuttle 打了个那个错误出来。
